/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RankingPackage;

import FrontEnd.fileManager;
import GamePackage.Player;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user-ubunto
 */
public class rankingFrame extends javax.swing.JFrame {
    Ranking rankingToUse;
    DefaultTableModel model;
    
    
    /**
     * Creates new form rankingFrame
     */
    public rankingFrame() {
        initComponents();
        this.model = (DefaultTableModel) this.jTable1.getModel();
        Ranking ranking = new Ranking();        
        fileManager controlLoad = new fileManager();
        ranking = controlLoad.loadRanking();
        this.rankingToUse = ranking;
        this.radioButtonsInGroup();
        reviewRadioButtons();
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSorted = new javax.swing.ButtonGroup();
        buttonGroupTypeOrder = new javax.swing.ButtonGroup();
        buttonGroupTypePlayer = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelSortedBy = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        RadioButtonName = new javax.swing.JRadioButton();
        RadioButtonRichness = new javax.swing.JRadioButton();
        PanelTypePlayer = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        RadioButtonAll = new javax.swing.JRadioButton();
        RadioButtonWinners = new javax.swing.JRadioButton();
        RadioButtonLosers = new javax.swing.JRadioButton();
        PanelTypeOrder = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        RadioButtonUpward = new javax.swing.JRadioButton();
        RadioButtonDown = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ranking de Jugadores");

        jLabel2.setText("Ordenados Por");

        RadioButtonName.setText("Nombre");
        RadioButtonName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonNameActionPerformed(evt);
            }
        });

        RadioButtonRichness.setText("Riqueza");
        RadioButtonRichness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonRichnessActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSortedByLayout = new javax.swing.GroupLayout(PanelSortedBy);
        PanelSortedBy.setLayout(PanelSortedByLayout);
        PanelSortedByLayout.setHorizontalGroup(
            PanelSortedByLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
            .addComponent(RadioButtonName)
            .addComponent(RadioButtonRichness)
        );
        PanelSortedByLayout.setVerticalGroup(
            PanelSortedByLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSortedByLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioButtonName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(RadioButtonRichness))
        );

        jLabel4.setText("Tipo de Jugadores");

        RadioButtonAll.setText("Todos");
        RadioButtonAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonAllActionPerformed(evt);
            }
        });

        RadioButtonWinners.setText("Solo ganadores");
        RadioButtonWinners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonWinnersActionPerformed(evt);
            }
        });

        RadioButtonLosers.setText("Solo Perdedores");
        RadioButtonLosers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonLosersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelTypePlayerLayout = new javax.swing.GroupLayout(PanelTypePlayer);
        PanelTypePlayer.setLayout(PanelTypePlayerLayout);
        PanelTypePlayerLayout.setHorizontalGroup(
            PanelTypePlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4)
            .addComponent(RadioButtonAll)
            .addComponent(RadioButtonLosers)
            .addComponent(RadioButtonWinners)
        );
        PanelTypePlayerLayout.setVerticalGroup(
            PanelTypePlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTypePlayerLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioButtonAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioButtonWinners)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(RadioButtonLosers))
        );

        jLabel3.setText("Tipo de Orden");

        RadioButtonUpward.setText("Ascendente");
        RadioButtonUpward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonUpwardActionPerformed(evt);
            }
        });

        RadioButtonDown.setText("Descendente");
        RadioButtonDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonDownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelTypeOrderLayout = new javax.swing.GroupLayout(PanelTypeOrder);
        PanelTypeOrder.setLayout(PanelTypeOrderLayout);
        PanelTypeOrderLayout.setHorizontalGroup(
            PanelTypeOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3)
            .addComponent(RadioButtonUpward)
            .addComponent(RadioButtonDown)
        );
        PanelTypeOrderLayout.setVerticalGroup(
            PanelTypeOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTypeOrderLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioButtonUpward)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioButtonDown)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(PanelSortedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(PanelTypeOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(PanelTypePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelTypePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PanelSortedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelTypeOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Nombre de Jugador", "Riqueza", "Ha ganado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadioButtonNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonNameActionPerformed
        reviewRadioButtons();
    }//GEN-LAST:event_RadioButtonNameActionPerformed

    private void RadioButtonRichnessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonRichnessActionPerformed
        reviewRadioButtons();
    }//GEN-LAST:event_RadioButtonRichnessActionPerformed

    private void RadioButtonUpwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonUpwardActionPerformed
        reviewRadioButtons();
    }//GEN-LAST:event_RadioButtonUpwardActionPerformed

    private void RadioButtonDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonDownActionPerformed
        reviewRadioButtons();
    }//GEN-LAST:event_RadioButtonDownActionPerformed

    private void RadioButtonAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonAllActionPerformed
        reviewRadioButtons();
    }//GEN-LAST:event_RadioButtonAllActionPerformed

    private void RadioButtonWinnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonWinnersActionPerformed
        reviewRadioButtons();
    }//GEN-LAST:event_RadioButtonWinnersActionPerformed

    private void RadioButtonLosersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonLosersActionPerformed
        reviewRadioButtons();
    }//GEN-LAST:event_RadioButtonLosersActionPerformed
    
    public void radioButtonsInGroup(){
        this.buttonGroupSorted.add(this.RadioButtonName);
        this.buttonGroupSorted.add(this.RadioButtonRichness);
        this.buttonGroupTypeOrder.add(this.RadioButtonUpward);
        this.buttonGroupTypeOrder.add(this.RadioButtonDown);
        this.buttonGroupTypePlayer.add(this.RadioButtonAll);
        this.buttonGroupTypePlayer.add(this.RadioButtonWinners);
        this.buttonGroupTypePlayer.add(this.RadioButtonLosers);
        this.RadioButtonDown.setSelected(true);
        this.RadioButtonLosers.setSelected(true);
        this.RadioButtonName.setSelected(true);
    }
    
    public void reviewRadioButtons(){
        removeRows();
        String typePlayer = "";
        String typeOrder = "";
        String typeSort = "";
        if (this.RadioButtonWinners.isSelected() == true) {
            typePlayer = "Win";
        }else if (this.RadioButtonLosers.isSelected() == true) {
            typePlayer = "Lose";
        }else if (this.RadioButtonAll.isSelected() == true) {
            typePlayer = "All";
        }
        if (this.RadioButtonName.isSelected() == true) {
            typeSort = "Name";
        }else if (this.RadioButtonRichness.isSelected() == true) {
            typeSort = "Rich";
        }
        if (this.RadioButtonUpward.isSelected() == true) {
            typeOrder = "Up";
        }else if (this.RadioButtonDown.isSelected() == true) {
            typeOrder = "Down";
        }        
        showAllPlayers(this.rankingToUse.sortBy(typePlayer, typeOrder, typeSort));
    }
    
    
    
    public void showAllPlayers(Player[] players){        
        Player[] playersToShow = players;        
        for (int i = 0; i < playersToShow.length; i++) {
            String name = playersToShow[i].getName();
            double richnness = playersToShow[i].getRichness();
            boolean win = playersToShow[i].isWin();
            String winner = "";
            if (win == true) {
                winner = "Si";
            }else{
                winner = "No";
            }
            this.model.addRow(new Object[]{name,richnness,winner});
        }
    }
        
    public void removeRows(){
        int rows=this.jTable1.getRowCount();
        for (int i = 0;i < rows; i++) {
            this.model.removeRow(0);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelSortedBy;
    private javax.swing.JPanel PanelTypeOrder;
    private javax.swing.JPanel PanelTypePlayer;
    private javax.swing.JRadioButton RadioButtonAll;
    private javax.swing.JRadioButton RadioButtonDown;
    private javax.swing.JRadioButton RadioButtonLosers;
    private javax.swing.JRadioButton RadioButtonName;
    private javax.swing.JRadioButton RadioButtonRichness;
    private javax.swing.JRadioButton RadioButtonUpward;
    private javax.swing.JRadioButton RadioButtonWinners;
    private javax.swing.ButtonGroup buttonGroupSorted;
    private javax.swing.ButtonGroup buttonGroupTypeOrder;
    private javax.swing.ButtonGroup buttonGroupTypePlayer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
