/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import BoardPackage.Board;
import GamePackage.Game;
import SectionsPackage.BasicService;
import SectionsPackage.Jail;
import SectionsPackage.Neutro;
import SectionsPackage.Place;
import SectionsPackage.Property;
import SectionsPackage.Section;
import SectionsPackage.Start;
import SectionsPackage.TakeOne;
import SectionsPackage.Trap;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import static javax.swing.JFileChooser.APPROVE_OPTION;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author user-ubunto
 */
public class CreateBoardFrame extends javax.swing.JFrame implements ComponentListener, ActionListener{
    private JButton[][] temporalySections = null;
    public Board board;
    private int rows;
    private int columns;
    private Game game;
    
    /**
     * Creates new form CreateGameFrame
     * @param rows
     * @param columns
     * @param game
     */
    public CreateBoardFrame(int rows,int columns,Game game) {        
        initComponents();
        this.rows = rows;
        this.columns = columns;
        createButtonsInPanel(this.jPanel1);        
        this.game = game;
        this.board = this.game.getGameBoard();
        resizePanelTable();
        initTable();
        showAllInTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ButtonCreate = new javax.swing.JButton();
        CreateGroupCards = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablePreview = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(385, 300));
        setResizable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 363, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 222, Short.MAX_VALUE)
        );

        ButtonCreate.setText("Crear");
        ButtonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCreateActionPerformed(evt);
            }
        });

        CreateGroupCards.setText("Grupos de Tarjetas");
        CreateGroupCards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateGroupCardsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreateGroupCards, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(ButtonCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CreateGroupCards, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(ButtonCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        TablePreview.setFocusable(false);
        jScrollPane1.setViewportView(TablePreview);

        jLabel1.setText("Vista Previa");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 218, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCreateActionPerformed
        this.game.setTurnSectionsEmpty();
        boolean isReady = this.game.reviewMap();
        boolean boardCreated = false;
        if (isReady == true) {
            fileManager fileM = new fileManager();
            try {
                JFileChooser fileChooser = new JFileChooser();
                fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("game.board", "board"));
                fileChooser.setAcceptAllFileFilterUsed(false);
                int seleccion = fileChooser.showSaveDialog(this);
                if (seleccion == APPROVE_OPTION) {
                    fileM.saveBoard(fileChooser.getSelectedFile().getPath()+".board", this.game);
                    boardCreated = true;
                }
            } catch (HeadlessException  e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Info", JOptionPane.ERROR_MESSAGE);
            }
            if (boardCreated) {
                JOptionPane.showMessageDialog(null, "Tablero Creado con Exito");
                this.dispose();
            }            
        }else{
            JOptionPane.showMessageDialog(null, "Error al crear Tablero");
        }
    }//GEN-LAST:event_ButtonCreateActionPerformed

    private void CreateGroupCardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateGroupCardsActionPerformed
        CreateGroupCard groupCards = new CreateGroupCard(this.board);
        groupCards.setVisible(true);        
    }//GEN-LAST:event_CreateGroupCardsActionPerformed
           
    
    
    private void initTable(){
        DefaultTableModel model = new DefaultTableModel(this.rows,this.columns);
        this.TablePreview.setModel(model);
    }
    
    private void createButtonsInPanel(Container pane) {
       this.temporalySections = new JButton[this.rows][this.columns];
        for (int i = 0; i < this.rows; i++) {
            for (int j = 0; j < this.columns; j++) {
                CreateBoard temp = new CreateBoard(i,j);
                pane.add(temp.getTempButton());
                temp.setBoundsButtons(i,j);
                this.temporalySections[i][j] = temp.getTempButton();               
                this.temporalySections[i][j].addActionListener(this);
            }
        }
        this.addComponentListener(this);        
    }
    
    private void resizePanelTable(){
        this.jPanel3.setBounds((this.columns)*80,60, WIDTH, HEIGHT);
        this.jPanel3.setSize(new Dimension(((this.columns)*80), ((this.rows+1)*70)+35));
    }
    
    private void resizePanelBoard(){
        if (this.columns*70 > 363 || this.rows*80 > 222) {
            this.jPanel1.setSize(new Dimension(((this.columns)*80), ((this.rows+1)*70)+35));        
            this.setSize(new Dimension(((this.columns)*80)*2, ((this.rows+1)*70)+35));            
        }
        
    }
    
    private void showAllInTable(){        
        Section[][] allSections = this.board.getSectionsBoard();
        for (int i = 0; i < this.rows; i++) {
            for (int j = 0; j < this.columns; j++) {
                try{
                    addItemPanelTable(verifyName(allSections[i][j]),i,j);
                }catch(NullPointerException e){
                    
                }                
            }            
        }                
    }
    
    private String verifyName(Section section){
        String name = "";
        if (section instanceof BasicService) {
            name = "Servicio";
        }else if (section instanceof Jail) {
            name = "Carcel";
        }else if (section instanceof Neutro) {
            name = "Neutro";
        }else if (section instanceof Property) {
            name = "Propiedad";
        }else if (section instanceof Start) {
            name = "Inicio";
        }else if (section instanceof TakeOne) {
            name = "Toma una Tarjeta";
        }else if (section instanceof Trap) {
            name = "Trampa";
        }        
        return name;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCreate;
    private javax.swing.JButton CreateGroupCards;
    private javax.swing.JTable TablePreview;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentResized(ComponentEvent e) {
        resizePanelBoard();
        resizePanelTable();
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void componentMoved(ComponentEvent e) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void componentShown(ComponentEvent e) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void componentHidden(ComponentEvent e) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        SectionOptions options = new SectionOptions(e.getActionCommand(),this.board, this,this.game);
        options.setVisible(true);
    }

    void addItemPanelTable(String name,int row, int column) {
        TableColumn columna = this.TablePreview.getColumnModel().getColumn(column);  
        ChangeCellColor TableCellRenderer = new ChangeCellColor();
        TableCellRenderer.setColumn(column);
        TableCellRenderer.setRow(row);
        columna.setCellRenderer(TableCellRenderer);
        this.TablePreview.setValueAt(name, row, column);              
    }


    
}
