/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import BoardPackage.Board;
import GamePackage.Game;
import javax.swing.JOptionPane;

/**
 *
 * @author user-ubunto
 */
public class CreateGameFrame extends javax.swing.JFrame {
    public Game gameToEdit;
    public boolean isGameToEdit;
    /**
     * Creates new form CreateGameFrame
     */
    public CreateGameFrame(Game gameToEdit) {
        initComponents();
        if (gameToEdit == null) {
            this.isGameToEdit = false;
        }else if(gameToEdit != null){
            this.gameToEdit = gameToEdit;
            showGameToEdit();
            this.isGameToEdit = true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TextFieldName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TextFieldInitialMoney = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TextFieldLapMoney = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TextFieldLimitHouses = new javax.swing.JTextField();
        TextFieldLimitHotels = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        SpinnerNumberDices = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        TextFieldInitialRows = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TextFieldInitialColumns = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        SpinnerMortgage = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre del Juego");

        jLabel5.setText("Dinero inicial");

        TextFieldInitialMoney.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldInitialMoneyKeyTyped(evt);
            }
        });

        jLabel6.setText("Dinero por vuelta");

        TextFieldLapMoney.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldLapMoneyKeyTyped(evt);
            }
        });

        jLabel7.setText("Limite de Casas");

        TextFieldLimitHouses.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldLimitHousesKeyTyped(evt);
            }
        });

        TextFieldLimitHotels.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldLimitHotelsKeyTyped(evt);
            }
        });

        jLabel8.setText("Limite de Hoteles");

        jLabel9.setText("Porcentaje de hipoteca");

        jLabel10.setText("%");

        jLabel11.setText("Numero de Dados");

        SpinnerNumberDices.setModel(new javax.swing.SpinnerNumberModel(1, 1, 3, 1));

        jLabel12.setText("Cantidad Filas");

        TextFieldInitialRows.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TextFieldInitialRows.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldInitialRowsKeyTyped(evt);
            }
        });

        jLabel13.setText("Cantidad Columnas");

        TextFieldInitialColumns.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldInitialColumnsKeyTyped(evt);
            }
        });

        jButton1.setText("Crear Juego");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        SpinnerMortgage.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextFieldName))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(SpinnerNumberDices, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel12)
                    .addComponent(TextFieldInitialRows, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextFieldInitialColumns, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SpinnerMortgage, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(TextFieldLimitHouses, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(TextFieldLimitHotels, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TextFieldInitialMoney, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextFieldLapMoney, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldInitialMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldLapMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldLimitHouses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldLimitHotels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SpinnerNumberDices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldInitialRows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldInitialColumns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SpinnerMortgage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldInitialRowsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldInitialRowsKeyTyped
        validateOnlyNumbers(evt);
    }//GEN-LAST:event_TextFieldInitialRowsKeyTyped

    private void TextFieldInitialColumnsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldInitialColumnsKeyTyped
        validateOnlyNumbers(evt);
    }//GEN-LAST:event_TextFieldInitialColumnsKeyTyped

    private void TextFieldInitialMoneyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldInitialMoneyKeyTyped
        validateOnlyNumbers(evt);
    }//GEN-LAST:event_TextFieldInitialMoneyKeyTyped

    private void TextFieldLapMoneyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldLapMoneyKeyTyped
        validateOnlyNumbers(evt);
    }//GEN-LAST:event_TextFieldLapMoneyKeyTyped

    private void TextFieldLimitHousesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldLimitHousesKeyTyped
        validateOnlyNumbers(evt);
    }//GEN-LAST:event_TextFieldLimitHousesKeyTyped

    private void TextFieldLimitHotelsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldLimitHotelsKeyTyped
        validateOnlyNumbers(evt);
    }//GEN-LAST:event_TextFieldLimitHotelsKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean readyToCreate = true;       
        if (this.TextFieldName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,"Debes ingresar un nombre al juego");
            readyToCreate = false;
        }else if(this.TextFieldInitialColumns.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Debes ingresar una cantidad de Columnas");
            readyToCreate = false;
        }else if(this.TextFieldInitialRows.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Debes ingresar una cantidad de Filas");
            readyToCreate = false;
        }else if(this.TextFieldInitialMoney.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Debes ingresar una cantidad de Dinero inicial");
            readyToCreate = false;
        }else if(this.TextFieldLapMoney.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Debes ingresar una cantidad de Dinero por Vuelta");
            readyToCreate = false;
        }else if(this.TextFieldLimitHouses.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Debes ingresar una cantidad Limite de casas");
            readyToCreate = false;
        }else if(this.TextFieldLimitHotels.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Debes ingresar una cantidad Limite de hoteles");
            readyToCreate = false;
        }        
        String nameGame = this.TextFieldName.getText();
        int numberDices = (int)(this.SpinnerNumberDices.getValue());            
        double initialMoney = Double.parseDouble(this.TextFieldInitialMoney.getText());
        double lapMoney = Double.parseDouble(this.TextFieldLapMoney.getText());
        int limitHouses = Integer.parseInt(this.TextFieldLimitHouses.getText());
        int limitHotels = Integer.parseInt(this.TextFieldLimitHotels.getText());
        int percentageMortgage = (int)(this.SpinnerMortgage.getValue());
            
        if (readyToCreate == true && this.isGameToEdit == false) {            
            Board gameBoard = new Board(Integer.parseInt(this.TextFieldInitialRows.getText()),Integer.parseInt(this.TextFieldInitialColumns.getText()));
            Game game = new Game(numberDices,initialMoney,lapMoney,limitHouses,limitHotels,percentageMortgage,gameBoard,nameGame);
            CreateBoardFrame createGameFrame = new CreateBoardFrame(Integer.parseInt(this.TextFieldInitialRows.getText()),Integer.parseInt(this.TextFieldInitialColumns.getText()),game);
            createGameFrame.setVisible(true);
            this.dispose();
        }
        if (readyToCreate == true && this.isGameToEdit == true) {
            int rows = Integer.parseInt(this.TextFieldInitialRows.getText());
            int columns = Integer.parseInt(this.TextFieldInitialColumns.getText());
            int columnsGame = this.gameToEdit.getGameBoard().getQuantityColumns();
            int rowsGame = this.gameToEdit.getGameBoard().getQuantityRows();
            
            if (rows != rowsGame || columns != columnsGame) {
                JOptionPane.showMessageDialog(null,"El Tablero sera reiniciado");
                Board gameBoard = new Board(Integer.parseInt(this.TextFieldInitialRows.getText()),Integer.parseInt(this.TextFieldInitialColumns.getText()));
                this.gameToEdit.setGameBoard(gameBoard);                                
            }
            this.gameToEdit.setNameGame(nameGame);
            this.gameToEdit.setNumberDices(numberDices);
            this.gameToEdit.setInitialMoney(initialMoney);
            this.gameToEdit.setLapMoney(lapMoney);
            this.gameToEdit.setLimitHouses(limitHouses);
            this.gameToEdit.setLimitHotels(limitHotels);
            this.gameToEdit.setPercentageMortgage(((percentageMortgage)*1.00)/100);
            
            CreateBoardFrame createGameFrame = new CreateBoardFrame(Integer.parseInt(this.TextFieldInitialRows.getText()),Integer.parseInt(this.TextFieldInitialColumns.getText()),this.gameToEdit);                
            createGameFrame.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    public void showGameToEdit(){
        this.TextFieldName.setText(this.gameToEdit.getNameGame());
        this.TextFieldInitialColumns.setText(String.valueOf(this.gameToEdit.getGameBoard().getQuantityColumns()));
        this.TextFieldInitialRows.setText(String.valueOf(this.gameToEdit.getGameBoard().getQuantityRows()));
        this.TextFieldInitialMoney.setText(String.valueOf(this.gameToEdit.getInitialMoney()));
        this.TextFieldLapMoney.setText(String.valueOf(this.gameToEdit.getLapMoney()));
        this.TextFieldLimitHouses.setText(String.valueOf(this.gameToEdit.getLimitHouses()));
        this.TextFieldLimitHotels.setText(String.valueOf(this.gameToEdit.getLimitHotels()));
        this.SpinnerMortgage.setValue((int)(this.gameToEdit.getPercentageMortgage()*100));
        this.SpinnerNumberDices.setValue((int)(this.gameToEdit.getNumberDices()));                
    }
    
    public void validateOnlyNumbers(java.awt.event.KeyEvent evt){
        char validate = evt.getKeyChar();
        if (Character.isLetter(validate)) {
            evt.consume();
            JOptionPane.showMessageDialog(null,"Ingrese solo numeros");
        }
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SpinnerMortgage;
    private javax.swing.JSpinner SpinnerNumberDices;
    private javax.swing.JTextField TextFieldInitialColumns;
    private javax.swing.JTextField TextFieldInitialMoney;
    private javax.swing.JTextField TextFieldInitialRows;
    private javax.swing.JTextField TextFieldLapMoney;
    private javax.swing.JTextField TextFieldLimitHotels;
    private javax.swing.JTextField TextFieldLimitHouses;
    private javax.swing.JTextField TextFieldName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
