/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import SectionsPackage.BasicService;
import SectionsPackage.Place;
import SectionsPackage.Property;
import SectionsPackage.Section;
import SectionsPackage.Station;

/**
 *
 * @author user-ubunto
 */
public class PropertiesFrame extends javax.swing.JFrame {
    
    Property sectionToPrint;
    
    /**
     * Creates new form PropertiesFrame
     */
    public PropertiesFrame(Property section) {
        initComponents();
        this.sectionToPrint = section;
        this.typeSection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelName = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        LabelNameCost = new javax.swing.JLabel();
        LabelPriceMortgage = new javax.swing.JLabel();
        LabelCost = new javax.swing.JLabel();
        PanelPlace = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        LabelPriceHouse = new javax.swing.JLabel();
        LabelPriceHotel = new javax.swing.JLabel();
        LabelStayCostPerHouse = new javax.swing.JLabel();
        LabelStayCostPerHotel = new javax.swing.JLabel();
        LabelGroup = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout PanelNameLayout = new javax.swing.GroupLayout(PanelName);
        PanelName.setLayout(PanelNameLayout);
        PanelNameLayout.setHorizontalGroup(
            PanelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNameLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelNameLayout.setVerticalGroup(
            PanelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Precio de Hipoteca");

        LabelNameCost.setText("LabelCost");

        LabelPriceMortgage.setText("jLabel3");

        LabelCost.setText("jLabel4");

        jLabel5.setText("Precio Aumentado");

        jLabel6.setText("Por Casa:");
        jLabel6.setToolTipText("");

        jLabel7.setText("Por Hotel:");
        jLabel7.setToolTipText("");

        jLabel8.setText("Costo por Casa");

        jLabel11.setText("Costo por Hotel");

        jLabel9.setText("Grupo: ");

        LabelPriceHouse.setText("jLabel3");

        LabelPriceHotel.setText("jLabel3");

        LabelStayCostPerHouse.setText("jLabel3");

        LabelStayCostPerHotel.setText("jLabel3");

        LabelGroup.setText("jLabel3");

        javax.swing.GroupLayout PanelPlaceLayout = new javax.swing.GroupLayout(PanelPlace);
        PanelPlace.setLayout(PanelPlaceLayout);
        PanelPlaceLayout.setHorizontalGroup(
            PanelPlaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPlaceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPlaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(PanelPlaceLayout.createSequentialGroup()
                        .addGroup(PanelPlaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(48, 48, 48)
                        .addGroup(PanelPlaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelGroup)
                            .addComponent(LabelPriceHotel)
                            .addComponent(LabelPriceHouse)
                            .addComponent(LabelStayCostPerHouse)
                            .addComponent(LabelStayCostPerHotel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelPlaceLayout.setVerticalGroup(
            PanelPlaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPlaceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPlaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelPlaceLayout.createSequentialGroup()
                        .addGroup(PanelPlaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(LabelStayCostPerHouse))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addComponent(LabelStayCostPerHotel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelPlaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelPlaceLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addGroup(PanelPlaceLayout.createSequentialGroup()
                        .addComponent(LabelPriceHouse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelPriceHotel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelPlaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(LabelGroup))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(LabelNameCost))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelCost)
                    .addComponent(LabelPriceMortgage))
                .addContainerGap(49, Short.MAX_VALUE))
            .addComponent(PanelPlace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LabelPriceMortgage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNameCost)
                    .addComponent(LabelCost))
                .addGap(18, 18, 18)
                .addComponent(PanelPlace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(PanelName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 3, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * This method is used to show atributes the Property.
     */
    public void typeSection(){
        this.jLabel1.setText(this.sectionToPrint.getName());
        this.LabelPriceMortgage.setText(String.valueOf(this.sectionToPrint.getMortgagePrice()));
        if (this.sectionToPrint instanceof Place) {
            Place sectionPlace = (Place)this.sectionToPrint;
            this.LabelNameCost.setText("Costo de Estancia");
            this.LabelCost.setText(String.valueOf(sectionPlace.getStayCost()));
            this.LabelStayCostPerHouse.setText(String.valueOf(sectionPlace.getStayCostPerHouse()));
            this.LabelStayCostPerHotel.setText(String.valueOf(sectionPlace.getStayCostPerHotel()));
            this.LabelPriceHouse.setText(String.valueOf(sectionPlace.getPriceHouse()));
            this.LabelPriceHotel.setText(String.valueOf(sectionPlace.getPriceHotel()));
            this.LabelGroup.setText(String.valueOf(sectionPlace.getGroupPlace()));            
            this.PanelPlace.setVisible(true);
        }else if(this.sectionToPrint instanceof Station){
            Station sectionStation = (Station)this.sectionToPrint;                        
            this.LabelNameCost.setText("Costo de Uso");
            this.LabelCost.setText(String.valueOf(sectionStation.getUsageCost()));
            this.PanelPlace.setVisible(false);
        }else if(this.sectionToPrint instanceof BasicService){
            BasicService sectionBasicService = (BasicService)this.sectionToPrint;  
            this.LabelNameCost.setText("Costo de Servicio");
            this.LabelCost.setText(String.valueOf(sectionBasicService.getServiceCost()));
            this.PanelPlace.setVisible(false);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelCost;
    private javax.swing.JLabel LabelGroup;
    private javax.swing.JLabel LabelNameCost;
    private javax.swing.JLabel LabelPriceHotel;
    private javax.swing.JLabel LabelPriceHouse;
    private javax.swing.JLabel LabelPriceMortgage;
    private javax.swing.JLabel LabelStayCostPerHotel;
    private javax.swing.JLabel LabelStayCostPerHouse;
    private javax.swing.JPanel PanelName;
    private javax.swing.JPanel PanelPlace;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
